### ISSUE TITLE
Make config file adaptable for other fish TS-length model

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#115]
This and similar line of code under `transect_results._get_strata_sig_b` is where the empirical hake TS-length model is specified:

https://github.com/uw-echospace/EchoPro/blob/2c832292cb9cbae0b5bfd07c0b1ef328043d94c2/EchoPro/computation/transect_results.py#L99

To allow using the TS-length model for other species, replace these lines with a function that obtains the model from the species name from the config file.

**Comment by brandynlucca** [comment]
Model metadata are currently incorporated into `initialization_config.yml`: 

https://github.com/OSOceanAcoustics/echopop/blob/f244105852a86a7ea0fa887401321b39106e5c90/config_files/initialization_config.yml#L29-L39

However, a more efficient format would likely be necessary for cases where there are many species represented (e.g. an input spreadsheet). Right now, the calculation for `sigma_bs` is hard-coded for `pacific_hake`: 

https://github.com/OSOceanAcoustics/echopop/blob/f244105852a86a7ea0fa887401321b39106e5c90/echopop/survey.py#L440-L442

Otherwise, `strata_mean_sigma_bs` includes the argument `species_id` for designating the species-of-interest: 

https://github.com/OSOceanAcoustics/echopop/blob/f244105852a86a7ea0fa887401321b39106e5c90/echopop/survey.py#L400-L401

The remaining calculations then use `species_id` as a grouping variable for calculating `sigma_bs_mean`:

https://github.com/OSOceanAcoustics/echopop/blob/f244105852a86a7ea0fa887401321b39106e5c90/echopop/survey.py#L456-L477

Consequently, the function `strata_mean_sigma_bs` only requires minor tweaking to be compatible with multi-species analyses.

**Comment by brandynlucca** [comment]
The updated implementation in PR #241 enables any defined species (using their number code) to be included when calculating the mean $\sigma_{bs}$ for each stratum.

This can be closed once PR #241 is closed.

**Comment by brandynlucca** [comment]
This has been encapsulated within #289 and can therefore be closed.
