### ISSUE TITLE
Change package name?

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#144]
"EchoPro" is not very descriptive for the functionality of the package, and it might make sense to change the package name in the python revamp?

A couple I could think of:
- echobiome
- echopop: pop for population

From @valentina-s:
- echostock
- echostats: STock Assesment for Transect Surveys
- echo2biomass
- echokrige
- echocensus
- echorecords

@rebeccathomas-NOAA : Any thoughts on this?

**Comment by valentina-s** [comment]
one more: echostockasstic/echostochastic (*stock* *ass*essment)

**Comment by rebeccathomas-NOAA** [comment]
So excited to see some discussion of names!  Since we're not doing the actual "stock assessment," I think it's best to veer away from the stock assessment-related names, although I particularly like some of them (echoSTaTS!).  I thought Echokrige had a nice  simple ring to it.

**Comment by ElizabethMPhillips** [comment]
I like the idea of a name that isn't tied specifically to stock assessment, since in the future we envision other species (like krill) being included, right? 

Echokrige works, but I also like a name that denotes the process of classifying echoes to estimate biomass (echo --> biomass, or kriged biomass?), so the inclusion of "2" - like echo2biomass works well, in my mind. 

I'll keep brainstorming!

**Comment by rebeccathomas-NOAA** [comment]
Here are a couple more 
Echo2Ab  (Echo 2 Abundance, pronounced EchoTab)
Echo2B (Echo 2 Biomass, pronounced EchoTube)

I fine myself gravitating towards two-syllable names

**Comment by leewujung** [comment]
EchoBM?

**Comment by leewujung** [comment]
Ok, we temporarily settled down on `Echopop` from the check-in meeting!

**Comment by leewujung** [comment]
The repo and package have been renamed! Closing this now. 😁
