### ISSUE TITLE
Setting up base directory paths using `.env` file or similar mechanism, or dedicated test folder

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopop#151]
Currently there are a couple of important directory paths:

- For input files, `data_root_dir` in `survey_year_2019_config.yml`. See https://github.com/uw-echospace/EchoPro/blob/161163e293bd0024edd3fb1455a4103b3a213503/config_files/survey_year_2019_config.yml#L17
- The directory path for Matlab EchoPro report files used in the tests. This path must be hard-wired in the function `matlab_output_base_path()` in `tests/conftest.py`:  https://github.com/uw-echospace/EchoPro/blob/161163e293bd0024edd3fb1455a4103b3a213503/EchoPro/tests/conftest.py#L45

It's awkward to have a functioning local environment where `data_root_dir` and the path in `matlab_output_base_path()` are set to local paths, without impacting the code base with one's specific paths. The current setup should be generalized.

One option could be to use an `.env` file that is added to the `.gitignore` so it's not stored in the repo. This file would store environment variables with local file paths to use with `data_root_dir` and `matlab_output_base_path()`. The file can be read conveniently and flexibly with the Python library [python-dotenv](https://github.com/theskumar/python-dotenv).

For handling `data_root_dir`, another option is to treat the `survey_year_2019_config.yml` file provided in the repo as simply a template, where users would store their own configuration yaml files outside the clone directory. This would be a good practice anyways. But we also need a `survey_year_2019_config.yml` file in the repo to run the example notebooks. This could potentially be handled with instructions to place the base folder for the input files at a known path relative to the config file. Not great, but doable.

~There's a potential linkage between this issue and #106~ [@leewujung edit 2023/12/10 -- I've closed #106 since this issue supersedes that and there's no detailed info there.]

**Comment by leewujung** [comment]
I think we should go the route of making things easily accessible and configurable by making `survey_year_2019_config.yml` just a template. In fact, that name should change too. I don't think we should go the `.env` route on the user side because that is harder to handle for users not familiar with hidden files. 

Below are my suggestions:
- in the repo keep template config files and do not link them for example notebooks
- for example notebooks use data pulled from elsewhere such as google drive or buckets requiring credentials
- for tests use mock data that is generated potentially by shuffling/randomizing the values in the example input files now so nothing is "real", due to the concern of sharing data publicly

**Comment by leewujung** [comment]
This issue is outdated as we've added test data folders to enable using mock data for unit tests. I'll close this.
