### ISSUE TITLE
Apply pre-commit code formatter

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#167]
See https://github.com/uw-echospace/EchoPro/pull/164#pullrequestreview-1843066471 -- we can do this after kriging overhaul is done, so that the uniform format gets adopted when we are creating new bootstrapping functions.

**Comment by brandynlucca** [comment]
Just to provide additional context so I can reference this later to discern the logic/rationale for why I implemented these functions using a sort of monkey patch rather than just using the native `pandas.DataFrame.pipe` method.

There is certainly overlap between `patch_method_to_DataFrame` decorator and the associated functions (that will be renamed in via #164, but like `discretize_variable`) and the flexibility/extension of `pandas.DataFrame` that `.pipe` provides. My brain definitely prefers moving through pipes with chained method, e.g. `object.function(*args)`, rather than as independent functions/mutations, e.g. `function(object, *args)`. As you've pointed out, `.pipe` accomplishes the same task (it's almost as if `pipe` was intentionally designed that way or something...). So the (kind of) monkey patch feature in `patch_method_to_DataFrame` is (almost) entirely an aesthetic choice such that the difference for how `discretize_variable` is written out would be: 

```python
# the current (sort of) monkey patched pandas.DataFrame extension approach
specimen_grouped = (
    specimen_df_copy
    .assign( arbitrary_value = 1 )
    .discretize_variable( bin_values = length_intervals , bin_variable = 'length' )
    .assign( group = lambda x: np.where( x['sex'] == int(1) , 'male' , 'female' ) )
    .pipe( lambda df: pd.concat( [ df.loc[ df[ 'sex' ] != 3 ] , df.assign( group = 'all' ) ] ) )
    .assign( station = 2 )
)

# the 'let's not be beholden to Brandyn's mostly trivial and idiosyncratic code aesthetic preferences" approach
specimen_grouped = (
    specimen_df_copy
    .assign( arbitrary_value = 1 )
    .pipe( lambda df: discretize_variable( df , bin_values = length_intervals , bin_variable = 'length' ) )
    .assign( group = lambda x: np.where( x['sex'] == int(1) , 'male' , 'female' ) )
    .pipe( lambda df: pd.concat( [ df.loc[ df[ 'sex' ] != 3 ] , df.assign( group = 'all' ) ] ) )
    .assign( station = 2 )
)
```

**Comment by brandynlucca** [comment]
This appears to coincide with #226 and #232 and can therefore be closed.
