### ISSUE TITLE
Length data from Canadian trawls not being ingested correctly

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#236]
Canadian trawl data ended up being excluded from `proc_NASC_data.m` (specifically in `data_bio.hake_length_sex`)

**Comment by brandynlucca** [comment]
Thankfully, it appears that this is not actually a bug but rather an issue: 1) with my local environment (MATLAB version R2022a) where the GUI/widget input for `US/CAN/US&CAN` was not correctly passing inputs to the rest of the value due to a (possible?) firewall issue and 2) a misunderstanding in what the variable `catch_trawl_no` (among others) represented. Once the former was addressed, the biological information is appropriately passed for the `CAN` data. The latter issue created bugs within my hacked code when running the software without the GUI in a standalone script.

**Comment by brandynlucca** [comment]
This has been addressed and therefore will be closing this.
